### ISSUE TITLE
Prompt to resume install after failure

### ISSUE THREAD

**Issue by txoof** [txoof/PaperPi#15]
Prompt user to resume remote install after failure; provide "resume" path:
e.g.

```
After installing required packages, resume this install with;

sudo /tmp/paperpi_asd2312/install/install.sh
```

**Comment by aaronr8684** [comment]
Generated path/prompt via:
- https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
- https://www.baeldung.com/linux/find-bash-script-filename

Tested in shell script outside of install
