### ISSUE TITLE
Add the option for daemon (default) or user run

### ISSUE THREAD

**Issue by aaronr8684** [txoof/PaperPi#25]
I think it would be a nice to allow the user to choose if they don't want to install this as a service automatically, but give them the necessary commands to install it later if they change their mind.

**Comment by txoof** [comment]
I think after we sort this we'll be ready to squash the manage_modules branch and merge it with the main branch.  What do you think?
  
The plugin installer isn't super important at the moment as there's no big back-log of plugin submissions so I can manually merge in a few for now.

Then it's on to Omni EPD!

**Comment by aaronr8684** [comment]
Yea, let me work on this now. I just ran a quick test of the install.sh and it seems like everything is working as expected still.

**Comment by txoof** [comment]
resolved with PR #27
