### ISSUE TITLE
Confirm EPDLib changes carry over to PaperPi correctly

### ISSUE THREAD

**Issue by aaronr8684** [txoof/PaperPi#36]
Make sure EPDLib v0.6 is compatible and run a fresh install/test 
- [ ] Pending EPDLib publishing to PyPi
- [ ] Test install process (32/64)
- [ ] Confirm multiple screens

Screens tested:
- [ ] 2.13 BW
- [ ] 3.7 GREY
- [ ] 4.2 BWY
- [ ] 5.65 COLOR
- [ ] 7.5 BWR
- [ ] IT8951 9.7in Grayscale

**Comment by txoof** [comment]
Resolved with #79
