### ISSUE TITLE
Add greyscale and color support to PaperPi

### ISSUE THREAD

**Issue by aaronr8684** [txoof/PaperPi#38]
Confirm grey and color support
- [ ] Add framework support for modes
- [ ] Add documentation for PaperPi
- [ ] Add documentation for Plugins
- [ ] Create sample plugin to verify config / screen setup
- [ ] Confirm multiple screens / modes

Screens/modes tested:
- [ ] 2.13 BW
- [ ] 3.7 BW
- [ ] 3.7 GREY
- [ ] 4.2 BW
- [ ] 4.2 BWY
- [ ] 5.65 BW
- [ ] 5.65 COLOR
- [ ] 7.5 BW
- [ ] 7.5 BWR

**Comment by txoof** [comment]
Resolved via #79
