### ISSUE TITLE
Numpy import issue

### ISSUE THREAD

**Issue by aaronr8684** [txoof/PaperPi#40]
Ran across this. For now, just documenting. Once we get a stable test build, I can confirm if it's still an issue. 

Error (not all of it):
```
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed. This error can happen for
different reasons, often due to issues with your setup.
```
`libf77blas.so.3: cannot open shared object file: No such file or directory`

Fix - https://numpy.org/devdocs/user/troubleshooting-importerror.html

`sudo apt-get install libatlas-base-dev`

**Comment by txoof** [comment]
This is definitely an issue I've run into when fiddling with Omni-EPD. The solution should be to add `libatlas-base-dev` to the [debian_packages-paperpi.txt](https://github.com/txoof/PaperPi/blob/development/paperpi/debian_packages-paperpi.txt) file.
