### ISSUE TITLE
rotation

### ISSUE THREAD

**Issue by adi170-alt** [txoof/PaperPi#48]
I really need to rotate my screen 180 degrees, I'm surprised that they didn't implement this feature yet

**Comment by adi170-alt** [comment]
bruh I am stupid, I didn't read the paperpi.ini completely.

**Comment by txoof** [comment]
@adi170-alt Glad you figured it out and thanks for closing the issue! Can't lie, it's great to see an issue history with a 1 hour lifespan that includes a resolution :).
