### ISSUE TITLE
Remote Installer

### ISSUE THREAD

**Issue by txoof** [txoof/PaperPi#8]
Install from a git repo through a `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/link)"` similar to the [homebrew](https://brew.sh/) installer.

**Comment by aaronr8684** [comment]
Alt command - `curl -fsSL https://rawlink > /tmp/remote_install.sh && sudo bash /tmp/remote_install.sh`

**Comment by aaronr8684** [comment]
Do you generate the README.md from the Jupyter file? I was going to work on it, but didn't want to make changes on the wrong side and have to make the changes twice.

**Comment by txoof** [comment]
Yeah, the source for most of the markdown is a ipynb. That's been my workflow up to now, but I'm not married to it. I know it's not super standard for most others. If that doesn't work for you, we can make a decision to ditch the .ipynb for the markdown. I can definitely live with MD for this 

I like the ipynb format because I can blend code and markdown as I need it.

**Comment by aaronr8684** [comment]
This is your project and it's not a big deal to work around your existing workflow. I just wanted to make sure I was making the changed on the upstream side of things 😄 

Do you have a preference on the format of the curl command?

**Comment by aaronr8684** [comment]
Final command tested:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/txoof/PaperPi/manage_modules/install/remote_install.sh)"`

**Comment by txoof** [comment]
I've added this to the README.
