### ISSUE TITLE
Scripted install from cloned repo

### ISSUE THREAD

**Issue by txoof** [txoof/PaperPi#9]
Install script in repo creates pipenv and installs paperpi locally for:
* Buster (32 bit)
* Bullseye (32 bit)
* Bullseye (64 bit)

Installer should:

- [x] Create pipenv venv
- [x] Install necessary Debian dependencies
- [x] Install correct python packages for arch 
     - [x] (handle differences between 32 and 64 bit versions of Bullseye)
- [x] Create executable 
- [x] Enable SPI automatically
- [x] Prompt user to edit paperpi.ini and open it automatically
- [x] Install systemd unit files and associated daemon user/group
- [x] Start service automatically if user has already edited the ini and all dependencies have been met

**Comment by aaronr8684** [comment]
If the goal is to build/run locally, do we want to put in a stop-gap fix for 64-bit? I guess it just boils down to how long you think it will be for the transition to complete. It's a pretty easy fix in the meantime

**Comment by aaronr8684** [comment]
So I don't think showing the screens during the install script is needed now that I think about it. They should be running the script from the Readme which will have the list right under the curl command. I would consider this done with PR #20
