### ISSUE TITLE
Can't get PaperPi to work after using install script

### ISSUE THREAD

**Issue by ypanle** [txoof/PaperPi#90]
I've installed Paperpi but when checking the log get an  could not load epd module epd7in3f -- error: unrecongized waveshare module: epd7in3f error

I have this in the config file

# CONFIG_VERSION=1.1
[main]
# waveshare display type use HD for IT8951 displays
display_type = epd7in3f

**Comment by txoof** [comment]
@ypanle 

I'll take a look into this.

Can you post your entire config file or at least the `[main]` section? That will help rule out problems.

**Comment by ypanle** [comment]
yeah for sure it's below 

# CONFIG_VERSION=1.1
[main]
# waveshare display type use HD for IT8951 displays
display_type = epd7in3f
# required vcom value for IT8951 screens
vcom = 0.0
# maximum refresh between total screen clear for HD displays
max_refresh = 4
# logging output level
log_level = WARNING
# display splash screen (True or False)
splash = True
# rotation of EPD display 
# (cable bottom: 0; cable left: -90; cable right: 90; cable top: 180)
rotation = 0
# mirror screen outuput - useful if output to screen appears backwards
mirror = False
# Enable RGB color support for 7-color screens (Default: True)
# This setting only affects 7 color screens and does not impact bi-color screens
# color = False

**Comment by ypanle** [comment]
yeah sure the main config is below

CONFIG_VERSION=1.1
[main]
#waveshare display type use HD for IT8951 displays
display_type = epd7in3f
#required vcom value for IT8951 screens
vcom = 0.0
#maximum refresh between total screen clear for HD displays
max_refresh = 4
#logging output level
log_level = WARNING
#display splash screen (True or False)
splash = True
#rotation of EPD display 
#(cable bottom: 0; cable left: -90; cable right: 90; cable top: 180)
rotation = 0
#mirror screen outuput - useful if output to screen appears backwards
mirror = False
#Enable RGB color support for 7-color screens (Default: True)
#This setting only affects 7 color screens and does not impact bi-color screens
#color = False

**Comment by txoof** [comment]
@ypanle 

Config looks good. I think I found the problem - the waveshare libraries were out of sync between the development and main branches.

I have a version here that should work `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/txoof/PaperPi/main/install/remote_install_development.sh)"`

Would you mind testing it before I push it to the main branch?

**Comment by ypanle** [comment]
That seems to be working!

**Comment by txoof** [comment]
Fantastic! I'll merge it into the main branch shortly

**Comment by txoof** [comment]
Fantastic! I'll merge it into the main branch shortly

**Comment by txoof** [comment]
Merged and ready to go if you want to install from the main branch. Thanks for catching this.
